# Project identification
sonar.projectKey=automated-banking-system
sonar.projectName=Automated Banking System
sonar.projectVersion=1.0

# Paths
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

# Encoding
sonar.sourceEncoding=UTF-8

# If using token authentication (recommended)
sonar.token=sqp_f608730541002f6156381af5f29e569249a99820



## Optional: Coverage (if you integrate JaCoCo later)
#sonar.java.coveragePlugin=jacoco
